### ISSUE TITLE
Image format to be uploaded

### ISSUE THREAD

**Issue by arjunmann73** [arjunmann73/SightSG#3]
In CameraController.dart, _selectedFile is the final Image after cropping, right? Which image (cropped or normal) needs to be stored? 
Need to know the reference to the image in order to store it as well.

**Comment by alexlim510** [comment]
I've just pushed a commit: 2c532033812a459e4ddee80795ab80489e58851a
In HomePageUI, the variable selectedImage contains the image.
The image is obtained from getCroppedImage from CameraController.
